# curl --request POST -v http://localhost:5000/products
GET http://localhost/products

###

# curl --request GET -v http://localhost:5000/product/2
GET http://localhost:5000/product/2

###

# curl --request POST -v http://localhost:5000/product
POST http://localhost/product
Content-Type: application/json

{
    "id": 1,
    "name": "new detail product"
}

###

# curl --request PUT -v http://localhost:5000/product/2
PUT http://localhost/product/100
Content-Type: application/json

{
    "name": "new detail product 100"
}

###

# curl --request DELETE -v http://localhost:5000/product/2
DELETE http://localhost/product/2

###
